import { formatCents, formatDeadline, parseCampaignPrice } from "../../admin/model";

import type { useCampaignEditor } from '../useCampaignEditor';
type Props=Pick<ReturnType<typeof useCampaignEditor>, 'campaignName' | 'representative' | 'deadline' | 'receiverId' | 'receivers' | 'goToCampaignStep' | 'selectedCampaignModels' | 'summaryColorCount' | 'summarySizeCount' | 'couponEnabled' | 'couponCode' | 'couponMinimumQuantity' | 'couponMaximumQuantity' | 'couponDiscounts' | 'mockupEnabled' | 'realPhotosEnabled' | 'editing'>;
export function ReviewStep({campaignName, representative, deadline, receiverId, receivers, goToCampaignStep, selectedCampaignModels, summaryColorCount, summarySizeCount, couponEnabled, couponCode, couponMinimumQuantity, couponMaximumQuantity, couponDiscounts, mockupEnabled, realPhotosEnabled, editing}:Props) { return (<section className="campaign-step campaign-step--review" aria-labelledby="campaign-review-title">
                  <header><span className="kicker">Etapa 4 de 4</span><h4 id="campaign-review-title">Revise antes de publicar</h4><p>Confira os principais dados. Você pode voltar a qualquer etapa para ajustar.</p></header>
                  <div className="campaign-review-grid">
                    <article><span className="material-symbols-rounded" aria-hidden="true">campaign</span><div><small>Campanha</small><strong>{campaignName || "Nome ainda não informado"}</strong><p>{representative || "Representante não informado"} · {deadline ? formatDeadline(new Date(`${deadline}T23:59:59`).toISOString()) : "Prazo não informado"}</p></div><button type="button" onClick={() => goToCampaignStep("information")}>Editar</button></article>
                    <article><span className="material-symbols-rounded" aria-hidden="true">checkroom</span><div><small>Produtos</small><strong>{selectedCampaignModels.map((model) => model.name === "Comum" ? "Padrão" : model.name).join(" e ") || "Nenhum corte"}</strong><p>{summaryColorCount} {summaryColorCount === 1 ? "cor" : "cores"} · {summarySizeCount} {summarySizeCount === 1 ? "tamanho" : "tamanhos"}</p></div><button type="button" onClick={() => goToCampaignStep("products")}>Editar</button></article>
                    <article><span className="material-symbols-rounded" aria-hidden="true">sell</span><div><small>Cupom</small><strong>{couponEnabled ? couponCode || "Código não informado" : "Sem cupom"}</strong><p>{couponEnabled ? `A partir de ${couponMinimumQuantity || 1} peças${couponMaximumQuantity ? ` · desconto em até ${couponMaximumQuantity} peças` : ""} · ${selectedCampaignModels.map((model) => `${model.name === "Comum" ? "Padrão" : model.name}: − ${formatCents(Math.round(parseCampaignPrice(couponDiscounts[model.name]) * 100))}`).join(" · ")}` : "A campanha seguirá com os preços normais"}</p></div><button type="button" onClick={() => goToCampaignStep("products")}>Editar</button></article>
                    <article><span className="material-symbols-rounded" aria-hidden="true">image</span><div><small>Apresentação</small><strong>{mockupEnabled && realPhotosEnabled ? "Mockup e fotos reais" : mockupEnabled ? "Mockup" : realPhotosEnabled ? "Fotos reais" : "Não configurada"}</strong><p>{realPhotosEnabled ? "Fotos e vídeo MP4 disponíveis por cor" : "Arte preparada para o mockup"}</p></div><button type="button" onClick={() => goToCampaignStep("images")}>Editar</button></article>
                    <article><span className="material-symbols-rounded" aria-hidden="true">wallet</span><div><small>Recebimento</small>{(() => { const receiver = receivers.find((item) => item.id === receiverId); return receiver ? <><strong>{receiver.name}</strong><p>Pagamentos na conta InfinitePay ${receiver.infinitepayHandle}</p></> : <><strong>Conta padrão da camisaria</strong><p>Nenhum recebedor específico escolhido</p></>; })()}</div><button type="button" onClick={() => goToCampaignStep("information")}>Editar</button></article>
                  </div>
                  <div className="campaign-review-ready"><span className="material-symbols-rounded" aria-hidden="true">verified</span><div><strong>{editing ? "Tudo pronto para salvar" : "Tudo pronto para publicar"}</strong><p>{editing ? "As alterações serão aplicadas mantendo o mesmo link e código." : "O link privado e o código de acesso serão gerados após a publicação."}</p></div></div>
                </section>); }
